/** d1-home 样式（命名空间 d1-*；不占用 .af-* 私有约定）。
 * 视觉与面板分组列表同语：实底圆角卡 + 发丝线 + 右对齐动作，深浅主题都看得见边。 */
export const CSS = [
  '.d1-entry{width:26px;height:26px;border-radius:50%;border:1px solid rgba(127,127,127,.5);background:transparent;color:inherit;display:inline-grid;place-items:center;padding:0;margin-left:6px;cursor:pointer;vertical-align:middle}',
  '.d1-entry:hover{border-color:#0a84ff;color:#0a84ff}',
  '.d1-roster{margin:18px 0 8px;padding:14px 16px 8px;border-radius:14px;background:var(--af-surface-2,var(--af-surface));border:1px solid var(--af-hairline-strong,var(--af-hairline));box-shadow:0 1px 2px rgba(0,0,0,.06)}',
  '.d1-head{margin:0 0 4px}',
  '.d1-title{font-size:15px;font-weight:700}',
  '.d1-sub{font-size:12px;color:var(--af-tertiary);margin-top:2px}',
  '.d1-warn{font-size:12px;color:var(--af-warn);margin:8px 0 0}',
  '.d1-home{margin-top:14px}',
  '.d1-home-t{font-size:14px;font-weight:700;display:flex;align-items:baseline;gap:0}',
  '.d1-home-s{font-weight:400;color:var(--af-tertiary);font-size:12px;margin-left:8px}',
  '.d1-n{margin-left:auto;font-size:11px;font-weight:600;color:var(--af-secondary);background:var(--af-surface);border:1px solid var(--af-hairline);border-radius:999px;padding:1px 9px;white-space:nowrap}',
  '.d1-row{display:flex;align-items:center;gap:10px;padding:11px 0}',
  '.d1-row+.d1-row{border-top:1px solid var(--af-hairline)}',
  '.d1-id{flex:1;min-width:0}',
  '.d1-who{font-size:15px;line-height:1.35}',
  '.d1-cap{display:block;font-size:12px;color:var(--af-tertiary);margin-top:1px}',
  '.d1-hdot{width:8px;height:8px;border-radius:50%;flex:none;background:#b0b3b8}',
  '.d1-h-online{background:#1a9e54}',
  '.d1-h-warn{background:#e6a700}',
  '.d1-move{font:inherit;font-size:13px;font-weight:600;padding:6px 15px;border-radius:10px;border:0;cursor:pointer;flex:none;background:rgba(10,132,255,.14);background:color-mix(in srgb,var(--af-accent,#0a84ff) 14%,transparent);color:var(--af-accent,#0a84ff)}',
  '.d1-move:disabled{opacity:.45;cursor:not-allowed}',
  '.d1-empty{padding:14px 0 8px;font-size:13px}',
  '.d1-empty-t{font-weight:700}',
  '.d1-empty-s{font-size:12px;color:var(--af-tertiary);margin-top:4px}',
  '.d1-undo{position:fixed;left:50%;bottom:24px;transform:translateX(-50%);z-index:1500;display:flex;align-items:center;gap:10px;font-size:13px;padding:10px 14px;border-radius:12px;background:#1c1c1e;color:#fff;box-shadow:0 8px 24px rgba(0,0,0,.3)}',
  '.d1-undo button{font:inherit;font-size:12.5px;font-weight:700;color:#fff;background:transparent;border:1px solid rgba(255,255,255,.5);border-radius:8px;padding:4px 10px;cursor:pointer}',
  '.d1-confirm{font-size:14px;line-height:1.7;padding:12px 14px;background:var(--af-bg,#fff);color:var(--af-primary);border-radius:12px;max-width:min(420px,88vw)}',
  '.d1-confirm-btns{display:flex;gap:8px;justify-content:flex-end;margin-top:12px}',
  '.d1-confirm-btns button{font:inherit;font-size:13px;padding:6px 14px;border-radius:9px;border:1px solid rgba(127,127,127,.45);background:transparent;color:inherit;cursor:pointer}',
  '.d1-confirmbox{position:fixed;inset:0;z-index:1600;display:flex;align-items:center;justify-content:center;background:rgba(0,0,0,.35);padding:20px}',
  '.d1-overlay{position:fixed;inset:0;z-index:1400;background:rgba(0,0,0,.42);display:flex;align-items:center;justify-content:center;padding:20px}',
  '.d1-peek{position:relative;width:min(480px,92vw);max-height:80vh;overflow:auto;background:var(--af-bg,#fff);color:var(--af-primary);border:1px solid var(--af-hairline-strong,transparent);border-radius:14px;padding:16px 18px 14px;box-shadow:0 24px 64px rgba(0,0,0,.35)}',
  '.d1-peek-t{font-size:14px;font-weight:700;margin-bottom:4px;padding-right:28px}',
  '.d1-peek-home{margin-top:12px}',
  '.d1-peek-h{font-size:12.5px;font-weight:700;color:var(--af-secondary)}',
  '.d1-peek-row{display:flex;align-items:center;gap:8px;font-size:13px;padding:6px 0}',
  '.d1-peek-row+.d1-peek-row{border-top:1px solid var(--af-hairline)}',
  '.d1-peek-go{font-size:12px;color:var(--af-tertiary);margin-top:12px}',
  '.d1-x{position:absolute;top:10px;right:10px;width:28px;height:28px;border-radius:50%;border:1px solid var(--af-hairline);background:transparent;color:inherit;font-size:15px;line-height:1;cursor:pointer;opacity:.7}',
  '@media (prefers-color-scheme: dark){.d1-confirmbox{background:rgba(0,0,0,.55)}.d1-peek{border-color:rgba(255,255,255,.10)}}',
].join('\n')
