
var VARIANTS = ["A","B","C","E","F","G","H"];
var NAMES = {A:"A 玄关灯",B:"B 全家福",C:"C 信箱",E:"E 第一天",F:"F 授勋",G:"G 第一句话",H:"H 拎包入住"};
var HINTS = {A:"A 玄关灯：一盏灯一句中央大按钮。",B:"B 全家福：一家之主加三小卡。",C:"C 信箱：家书加拆信。",E:"E 第一天：一生一次，DAY ONE。",F:"F 授勋：勋章加委任状，档案全是真数据。",G:"G 第一句话：HOME 就是一条消息，按钮是快捷回复。",H:"H 拎包入住：3/3 通关清单，全是真状态。"};
var qs = new URLSearchParams(location.search);
var variant = VARIANTS.indexOf(qs.get("variant")) >= 0 ? qs.get("variant") : "A";
var theme = "light", lastAct = "初始化";
function $(id){return document.getElementById(id);}
function bigBtn(main, sub){return '<div style="text-align:center;margin-top:26px"><button class="bigbtn" data-act="home">' + main + '<small>' + sub + '</small></button></div>';}
function vA(){return '<div style="display:flex;flex-direction:column;align-items:center;justify-content:center;min-height:520px;text-align:center;padding:30px"><div class="lamp">帅</div><div style="font-size:24px;font-weight:800;margin:22px 0 4px">小帅在家，等你开口</div><div style="font-size:13px;color:var(--mut)"><span class="dot on"></span>飞书在线 · 有事随时叫我</div>' + bigBtn("回家","点后这里永不再打扰") + '<div style="font-size:12px;color:var(--mut);margin-top:16px">飞书在线 &nbsp;·&nbsp; 1 个会话已就位 &nbsp;·&nbsp; 身份已装扮</div></div>';}
function vB(){return '<div style="padding:34px 30px"><div style="display:flex;gap:14px;align-items:center"><div class="lamp" style="width:64px;height:64px;font-size:28px;border-radius:18px">帅</div><div><div style="font-size:20px;font-weight:800">小帅一家</div><div style="font-size:12px;color:var(--mut)"><span class="dot on"></span>飞书在线 · 全员到齐</div></div></div><div class="cards3"><div class="mini"><h4><span class="dot on"></span>渠道在线</h4><p>飞书在线。断线 15 秒内知道，从不谎报离线。</p></div><div class="mini"><h4>会话就位</h4><p>1 个私聊已就位，点开即聊，无需翻找。</p></div><div class="mini"><h4>身份装扮</h4><p>PTC 模式 · 上下文开。见人说人话，进群有分寸。</p></div></div>' + bigBtn("回家看看","全家都在了") + '</div>';}
function vC(){return '<div style="padding:44px 24px"><div class="letter"><p>你不在的时候，我把门口收拾好了——</p><p>飞书在线，<b>1 个私聊会话</b>已经就位，随时可以开聊；预设和上下文都按你的意思装好了，进群知道分寸。</p><p>别在外面漂太久。</p><div class="sig">—— 小帅 · 刚刚</div></div>' + bigBtn("回家","拆信，即不再打扰") + '</div>';}
function vE(){return '<div style="display:flex;flex-direction:column;align-items:center;justify-content:center;min-height:520px;text-align:center;padding:30px"><div class="dayone">01</div><div style="font-size:13px;letter-spacing:.35em;color:var(--mut)">DAY ONE</div><div style="font-size:22px;font-weight:800;margin:14px 0 4px">今天是你们认识的第一天</div><div style="font-size:13px;color:var(--mut)">小帅会记住今天 · 这个页面一生只出现一次</div>' + bigBtn("回家","一生一次，点后永别") + '</div>';}
function vF(){return '<div style="padding:40px 24px;text-align:center"><div class="medal">帅</div><div class="cert"><h4>委 任 状</h4><p>兹任命 <b>小帅</b> 为本家守护者</p><p>麾下 <b>飞书在线</b> · 职级 <b>PTC 模式</b> · 心法 <b>上下文开</b></p></div>' + bigBtn("挂牌上任","受命，即不再打扰") + '</div>';}
function vG(){return '<div style="padding:60px 30px"><div style="display:flex;gap:12px;align-items:flex-end;max-width:600px;margin:0 auto"><div class="lamp" style="width:48px;height:48px;font-size:22px;border-radius:14px;flex:none">帅</div><div class="bubble"><b>小帅：</b>你终于来了，我是小帅。飞书那边 <b>1 个私聊会话</b>已经替你候着，进群的事也备好了。</div></div><div style="text-align:center;margin-top:22px"><button class="bigbtn" data-act="home" style="font-size:15px;padding:11px 34px">我回来了</button></div><div class="note">上面是小帅发来的第一条消息，下面是你唯一的快捷回复。</div></div>';}
function vH(){return '<div style="padding:40px 24px"><div style="text-align:center;font-size:22px;font-weight:800">拎包入住</div><div style="text-align:center;font-size:13px;color:var(--mut);margin:4px 0 14px">入住手续 3/3 已办妥</div><div class="checkrow"><span class="tick">✓</span><div><b>渠道接通</b><div style="font-size:12px;color:var(--mut)">飞书在线。断线 15 秒内知道，从不谎报离线。</div></div></div><div class="checkrow"><span class="tick">✓</span><div><b>会话就位</b><div style="font-size:12px;color:var(--mut)">1 个私聊已就位，点开即聊。</div></div></div><div class="checkrow"><span class="tick">✓</span><div><b>身份装扮</b><div style="font-size:12px;color:var(--mut)">PTC 模式 · 上下文开。</div></div></div>' + bigBtn("拎包入住","手续齐了，进门吧") + '</div>';}
function render(){document.getElementById("root").setAttribute("data-theme",theme);$("variantHint").textContent=HINTS[variant];var body=$("stage");var htm=variant==="A"?vA():variant==="B"?vB():variant==="C"?vC():variant==="E"?vE():variant==="F"?vF():variant==="G"?vG():vH();body.innerHTML=htm;$("swLabel").textContent=NAMES[variant];$("stateLine").textContent="变体 "+variant+" · 主题 "+theme+" · 上下文 mock（小帅/飞书在线/私聊1） · 上次操作："+lastAct+" URL ?variant="+variant;var box=$("dots");var dh="";for(var i=0;i<VARIANTS.length;i++){dh+='<button data-v="'+VARIANTS[i]+'" title="'+NAMES[VARIANTS[i]]+'" class="'+(VARIANTS[i]===variant?"on":"")+'"></button>';}box.innerHTML=dh;var dots=box.querySelectorAll("button");for(var j=0;j<dots.length;j++)(function(b){b.addEventListener("click",function(){setVariant(b.getAttribute("data-v"),"圆点直达");});})(dots[j]);if(new URLSearchParams(location.search).get("prod")==="1"){var sw=document.querySelector(".switcher");if(sw)sw.style.display="none";}}
function setVariant(v,why){if(VARIANTS.indexOf(v)<0)return;variant=v;var u=new URL(location.href);u.searchParams.set("variant",v);history.replaceState(null,"",u.toString());lastAct="切换变体 → "+NAMES[v]+(why?"（"+why+"）":"");render();}
$("themeSel").addEventListener("change",function(e){theme=e.target.value;lastAct="切换主题 → "+(theme==="dark"?"深色":"浅色");render();});
$("prevBtn").addEventListener("click",function(){var i=VARIANTS.indexOf(variant);setVariant(VARIANTS[(i+VARIANTS.length-1)%VARIANTS.length],"◀");});
$("nextBtn").addEventListener("click",function(){var i=VARIANTS.indexOf(variant);setVariant(VARIANTS[(i+1)%VARIANTS.length],"▶");});
document.addEventListener("click",function(e){var t=e.target;var b=t&&t.closest?t.closest('[data-act="home"]'):null;if(b){lastAct="点了回家（原型演示：真机将持久化并不再出现）";render();}});
document.addEventListener("keydown",function(e){var tag=(document.activeElement&&document.activeElement.tagName)||"";if(tag==="INPUT"||tag==="TEXTAREA")return;if(e.key==="ArrowRight"){var i=VARIANTS.indexOf(variant);setVariant(VARIANTS[(i+1)%VARIANTS.length],"键盘");}if(e.key==="ArrowLeft"){var k=VARIANTS.indexOf(variant);setVariant(VARIANTS[(k+VARIANTS.length-1)%VARIANTS.length],"键盘");}});
render();