/** DetailDrawer 命名空间样式：只出现 detail-drawer-* 类；颜色全部走 DSH 主题别名（深色自动跟随，fallback 浅色）。 */
export const CSS = [
'.detail-drawer-overlay{position:fixed;inset:0;z-index:1200;background:rgba(0,0,0,.45)}',
'.detail-drawer-sheet{position:fixed;left:50%;top:50%;transform:translate(-50%,-50%);width:min(720px,94vw);height:min(680px,90vh);z-index:1200;background:var(--dsw-alias-bg-base,#fff);color:var(--dsw-alias-label-primary,#1c1c1e);border:1px solid var(--dsw-alias-separator,#ddd);border-radius:16px;box-shadow:0 24px 64px rgba(0,0,0,.28);display:flex;flex-direction:column;overflow:hidden;font-size:13px}',
'.detail-drawer{display:flex;flex-direction:column;height:100%;min-height:0}',
'.detail-drawer-dhead{display:flex;align-items:center;gap:8px;padding:12px 14px;border-bottom:1px solid var(--dsw-alias-separator,#eee);font-weight:700}',
'.detail-drawer-dbody{flex:1;overflow-y:auto;padding:12px 14px;display:grid;gap:10px;align-content:start}',
'.detail-drawer-summary{border:1px solid var(--dsw-alias-separator,#eee);border-radius:13px;padding:4px 14px;background:var(--dsw-alias-bg-base,#fff)}',
'.detail-drawer-fld{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin:8px 0;font-size:12px}',
'.detail-drawer-lab{color:var(--dsw-alias-label-secondary,#888);min-width:44px}',
'.detail-drawer-summary select,.detail-drawer-sec input{max-width:100%;padding:5px 8px;border:1px solid var(--dsw-alias-separator,#ddd);border-radius:8px;font-size:12px;background:var(--dsw-alias-bg-base,#fff);color:inherit}',
'.detail-drawer-seg{display:inline-flex;border:1px solid var(--dsw-alias-separator,#ddd);border-radius:8px;overflow:hidden}',
'.detail-drawer-seg button{border:0;background:transparent;color:inherit;padding:4px 10px;font-size:12px;cursor:pointer}',
'/* 白字按钮底色用实色：宿主 brand 别名在真机可为白色，见 #26 评论 */',
'.detail-drawer-seg button.on{background:#0a84ff;color:#fff}',
'.detail-drawer-meta{font-size:11px;color:var(--dsw-alias-label-secondary,#888)}',
'.detail-drawer-sec{border:1px solid var(--dsw-alias-separator,#eee);border-radius:10px;padding:10px;background:var(--dsw-alias-bg-base,#fff)}',
'.detail-drawer-sec summary{cursor:pointer;font-size:12px;font-weight:700}',
'.detail-drawer-route{display:flex;align-items:center;gap:10px;padding:6px 0;border-bottom:1px solid var(--dsw-alias-separator,#eee);overflow-x:auto;white-space:nowrap}',
'.detail-drawer-rchat{font-size:12px;flex:none}',
'.detail-drawer-route code{font-size:11px;font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;flex:none}',
'.detail-drawer-ghost{border-left:3px solid var(--dsw-alias-state-warn-primary,#e8890c);padding-left:6px}',
'.detail-drawer-push{margin-left:auto;flex:none}',
'.detail-drawer-chrow{display:flex;gap:8px;align-items:center;font-size:12px;padding:5px 0;border-bottom:1px solid var(--dsw-alias-separator,#eee)}',
'.detail-drawer-dot{width:8px;height:8px;border-radius:50%;background:var(--dsw-alias-label-tertiary,#999)}',
'.detail-drawer-dot.online{background:var(--dsw-alias-state-success-primary,#20a162)}',
'.detail-drawer-dot.warn{background:var(--dsw-alias-state-warn-primary,#e8890c)}',
'.detail-drawer-dot.offline{background:var(--dsw-alias-state-error-primary,#d92d20)}',
'.detail-drawer-foot{display:flex;gap:8px}',
'.detail-drawer-cap{font-size:11px;font-weight:700;color:var(--dsw-alias-label-secondary,#888);margin:10px 4px 4px}',
'.detail-drawer-list{border:1px solid var(--dsw-alias-separator,#eee);border-radius:13px;padding:2px 14px;background:var(--dsw-alias-bg-base,#fff)}',
'.detail-drawer-nobox{border:0 !important;padding:2px 0 !important;background:transparent !important}',
'.detail-drawer-row{display:flex;align-items:center;gap:10px;min-height:48px;padding:8px 0;border-top:1px solid var(--dsw-alias-separator,#eee);font-size:13px}',
'.detail-drawer-row:first-child{border-top:0}',
'.detail-drawer-row .detail-drawer-lab{color:var(--dsw-alias-label-secondary,#888);flex:none}',
'.detail-drawer-row .detail-drawer-rval{margin-left:auto;display:flex;align-items:center;gap:8px;min-width:0;font-size:12px}',
'.detail-drawer-sw{position:relative;width:42px;height:24px;border-radius:999px;border:0;cursor:pointer;background:var(--dsw-alias-label-tertiary,#999);opacity:.55;flex:none;padding:0}',
'.detail-drawer-sw[aria-checked="true"]{background:var(--dsw-alias-state-success-primary,#20a162);opacity:1}',
'.detail-drawer-sw::after{content:"";position:absolute;top:3px;left:3px;width:18px;height:18px;border-radius:50%;background:#fff;transition:left .15s}',
'.detail-drawer-sw[aria-checked="true"]::after{left:21px}',
'.detail-drawer-sw:disabled{cursor:not-allowed;opacity:.35}',
'.detail-drawer-hero{width:100%;padding:11px !important;font-size:14px !important;border-radius:11px !important}',
'.detail-drawer-list .af-btn,.detail-drawer-foot .af-btn,.detail-drawer-sec .af-btn{border:1px solid var(--dsw-alias-separator,#3a3a3c) !important;background:var(--dsw-alias-bg-base,#1c1c1e)}',
'.detail-drawer-list .af-btn.primary,.detail-drawer-foot .af-btn.primary,.detail-drawer-sec .af-btn.primary{background:#0a84ff !important;border-color:transparent !important;color:#fff !important}',
'.detail-drawer-empty{font-size:12px;color:var(--dsw-alias-label-secondary,#888)}',
'.detail-drawer-ws{font-size:12px;word-break:break-all}',
'.detail-drawer-chlogo{display:inline-flex;width:16px;height:16px;align-items:center;justify-content:center;flex:none}',
'.detail-drawer-chlogo svg{width:16px;height:16px;display:block}',
'.detail-drawer-chbadge{border-radius:50%;background:#0a84ff;color:#fff;font-size:10px;font-weight:700}',
'.detail-drawer-chctx{border-top:1px solid var(--dsw-alias-separator,#eee);padding:6px 0;display:grid;gap:4px}',
'.detail-drawer-list textarea,.detail-drawer-sec textarea{display:block;width:100%;height:96px;box-sizing:border-box;padding:8px 10px;border:1px solid var(--dsw-alias-separator,#ddd);border-radius:8px;font:inherit;font-size:12px;background:var(--dsw-alias-bg-base,#fff);color:inherit;resize:none}',
'.detail-drawer-note{font-size:12px;word-break:break-all;background:var(--dsw-alias-bg-layer-1,#f6f8fa);color:var(--dsw-alias-label-primary,#1c1c1e);border:1px solid var(--dsw-alias-separator,#ddd);border-radius:8px;padding:6px 8px}',
].join('');
