/** c1a 命名空间样式：只出现 c1a-* 类；颜色全部走 DSH 主题别名（深色自动跟随，fallback 浅色）。 */
export const CSS = [
'.c1a-overlay{position:fixed;inset:0;z-index:1200;background:rgba(0,0,0,.45)}',
'.c1a-sheet{position:fixed;left:50%;top:50%;transform:translate(-50%,-50%);width:min(720px,94vw);height:min(680px,90vh);z-index:1200;background:var(--dsw-alias-bg-base,#fff);color:var(--dsw-alias-label-primary,#1c1c1e);border:1px solid var(--dsw-alias-separator,#ddd);border-radius:16px;box-shadow:0 24px 64px rgba(0,0,0,.28);display:flex;flex-direction:column;overflow:hidden;font-size:13px}',
'.c1a-drawer{display:flex;flex-direction:column;height:100%;min-height:0}',
'.c1a-dhead{display:flex;align-items:center;gap:8px;padding:12px 14px;border-bottom:1px solid var(--dsw-alias-separator,#eee);font-weight:700}',
'.c1a-dbody{flex:1;overflow-y:auto;padding:12px 14px;display:grid;gap:10px;align-content:start}',
'.c1a-summary{border:1px solid var(--dsw-alias-separator,#eee);border-radius:13px;padding:4px 14px;background:var(--dsw-alias-bg-base,#fff)}',
'.c1a-fld{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin:8px 0;font-size:12px}',
'.c1a-lab{color:var(--dsw-alias-label-secondary,#888);min-width:44px}',
'.c1a-summary select,.c1a-sec input{max-width:100%;padding:5px 8px;border:1px solid var(--dsw-alias-separator,#ddd);border-radius:8px;font-size:12px;background:var(--dsw-alias-bg-base,#fff);color:inherit}',
'.c1a-seg{display:inline-flex;border:1px solid var(--dsw-alias-separator,#ddd);border-radius:8px;overflow:hidden}',
'.c1a-seg button{border:0;background:transparent;color:inherit;padding:4px 10px;font-size:12px;cursor:pointer}',
'.c1a-seg button.on{background:var(--dsw-alias-brand-primary,#1677ff);color:#fff}',
'.c1a-meta{font-size:11px;color:var(--dsw-alias-label-secondary,#888)}',
'.c1a-sec{border:1px solid var(--dsw-alias-separator,#eee);border-radius:10px;padding:10px;background:var(--dsw-alias-bg-base,#fff)}',
'.c1a-sec summary{cursor:pointer;font-size:12px;font-weight:700}',
'.c1a-route{display:flex;align-items:center;gap:10px;padding:6px 0;border-bottom:1px solid var(--dsw-alias-separator,#eee);overflow-x:auto;white-space:nowrap}',
'.c1a-rchat{font-size:12px;flex:none}',
'.c1a-route code{font-size:11px;font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;flex:none}',
'.c1a-ghost{border-left:3px solid var(--dsw-alias-state-warn-primary,#e8890c);padding-left:6px}',
'.c1a-push{margin-left:auto;flex:none}',
'.c1a-chrow{display:flex;gap:8px;align-items:center;font-size:12px;padding:5px 0;border-bottom:1px solid var(--dsw-alias-separator,#eee)}',
'.c1a-dot{width:8px;height:8px;border-radius:50%;background:var(--dsw-alias-label-tertiary,#999)}',
'.c1a-dot.online{background:var(--dsw-alias-state-success-primary,#20a162)}',
'.c1a-dot.warn{background:var(--dsw-alias-state-warn-primary,#e8890c)}',
'.c1a-dot.offline{background:var(--dsw-alias-state-error-primary,#d92d20)}',
'.c1a-foot{display:flex;gap:8px}',
'.c1a-cap{font-size:11px;font-weight:700;color:var(--dsw-alias-label-secondary,#888);margin:10px 4px 4px}',
'.c1a-list{border:1px solid var(--dsw-alias-separator,#eee);border-radius:13px;padding:2px 14px;background:var(--dsw-alias-bg-base,#fff)}',
'.c1a-nobox{border:0 !important;padding:2px 0 !important;background:transparent !important}',
'.c1a-row{display:flex;align-items:center;gap:10px;min-height:48px;padding:8px 0;border-top:1px solid var(--dsw-alias-separator,#eee);font-size:13px}',
'.c1a-row:first-child{border-top:0}',
'.c1a-row .c1a-lab{color:var(--dsw-alias-label-secondary,#888);flex:none}',
'.c1a-row .c1a-rval{margin-left:auto;display:flex;align-items:center;gap:8px;min-width:0;font-size:12px}',
'.c1a-sw{position:relative;width:42px;height:24px;border-radius:999px;border:0;cursor:pointer;background:var(--dsw-alias-label-tertiary,#999);opacity:.55;flex:none;padding:0}',
'.c1a-sw[aria-checked="true"]{background:var(--dsw-alias-state-success-primary,#20a162);opacity:1}',
'.c1a-sw::after{content:"";position:absolute;top:3px;left:3px;width:18px;height:18px;border-radius:50%;background:#fff;transition:left .15s}',
'.c1a-sw[aria-checked="true"]::after{left:21px}',
'.c1a-sw:disabled{cursor:not-allowed;opacity:.35}',
'.c1a-hero{width:100%;padding:11px !important;font-size:14px !important;border-radius:11px !important}',
'.c1a-list .af-btn,.c1a-foot .af-btn,.c1a-sec .af-btn{border:1px solid var(--dsw-alias-separator,#3a3a3c) !important;background:var(--dsw-alias-bg-base,#1c1c1e)}',
'.c1a-list .af-btn.primary,.c1a-foot .af-btn.primary,.c1a-sec .af-btn.primary{background:var(--dsw-alias-brand-primary,#0a84ff) !important;border-color:transparent !important;color:#fff !important}',
'.c1a-empty{font-size:12px;color:var(--dsw-alias-label-secondary,#888)}',
'.c1a-ws{font-size:12px;word-break:break-all}',
'.c1a-chlogo{display:inline-flex;width:16px;height:16px;align-items:center;justify-content:center;flex:none}',
'.c1a-chlogo svg{width:16px;height:16px;display:block}',
'.c1a-chbadge{border-radius:50%;background:var(--dsw-alias-brand-primary,#1677ff);color:#fff;font-size:10px;font-weight:700}',
'.c1a-chctx{border-top:1px solid var(--dsw-alias-separator,#eee);padding:6px 0;display:grid;gap:4px}',
'.c1a-list textarea,.c1a-sec textarea{display:block;width:100%;height:96px;box-sizing:border-box;padding:8px 10px;border:1px solid var(--dsw-alias-separator,#ddd);border-radius:8px;font:inherit;font-size:12px;background:var(--dsw-alias-bg-base,#fff);color:inherit;resize:none}',
'.c1a-note{font-size:12px;word-break:break-all;background:var(--dsw-alias-bg-subtle,#f6f8fa);border-radius:8px;padding:6px 8px}',
].join('');
